In [1]:

student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

for i in range(len(student1)):
    scores = student1[i] + student2[i]
    print(scores)
    print("===============")

144
170
164
167
177


In [2]:
student1 = [69, 78, 72, 91, 85]
student2 = [75, 92, 92, 76, 92]

student1 + student2

[69, 78, 72, 91, 85, 75, 92, 92, 76, 92]

In [3]:
import numpy as np
from numpy import ndarray
student1:ndarray = np.array([69, 78, 72, 91, 85])
student2:ndarray = np.array([75, 92, 92, 76, 92])

#可以做陣列運算,不需使用for...in
totols:ndarray= student1 + student2
for total in totols:
    print(total)
    print("=========")

144
170
164
167
177


In [4]:
array:ndarray = np.array([[1,2,3],[4,5,6]])
print(array)
#property
#ndim,shape,size,dtype

print(array.ndim)
print(array.shape)
print(array.size)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6
int32


In [5]:
np.random.randint(50,101,size=(50, 5))

array([[ 63,  73,  54,  56,  83],
       [ 70,  69,  50,  96,  61],
       [ 72,  66,  75,  83,  71],
       [ 83,  51,  67,  59,  93],
       [ 90,  64,  80,  71,  89],
       [ 81,  85,  73,  60,  90],
       [ 70,  67,  83,  54,  84],
       [ 83,  65,  92,  69,  81],
       [ 95,  85,  75,  76,  54],
       [ 59,  90,  91,  72,  59],
       [ 54,  58,  78,  98,  50],
       [ 62,  68,  79, 100,  72],
       [ 71,  92,  90,  70,  99],
       [ 98,  54,  65,  70,  82],
       [ 69,  76,  65,  61,  68],
       [ 69,  94,  50,  67,  77],
       [ 71,  69,  65,  69,  67],
       [ 89,  60,  96,  91,  69],
       [ 87,  88,  76,  86,  64],
       [ 71,  59,  74,  71,  51],
       [ 60,  93,  56,  93,  60],
       [ 72,  86,  62,  94,  98],
       [ 72,  50,  57,  63,  74],
       [ 96,  51,  75,  70,  50],
       [ 91,  70,  99,  53,  53],
       [ 78,  89,  64,  74,  79],
       [ 50,  92,  55,  96,  89],
       [ 90,  84,  72,  60,  74],
       [ 67,  87,  63,  74,  55],
       [ 51,  